apiVersion: v1
kind: Service
metadata:
    name: "ddccservices-56e3"
    labels:
        app: "ddccservices-56e3"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "ddccservices-56e3"